<?php
// Required headers for a POST request
header("Access-Control-Allow-Origin: *");
header("Content-Type: application/json; charset=UTF-8");
header("Access-Control-Allow-Methods: POST");
header("Access-Control-Max-Age: 3600");
header("Access-Control-Allow-Headers: Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With");

include_once '../../config/database.php';

$database = new Database();
$db = $database->getConnection();

$data = json_decode(file_get_contents("php://input"));

// Check for missing data
if (!empty($data->title) && !empty($data->content) && !empty($data->target_audience) && !empty($data->admin_id)) {

    try {
        // 🛑 START TRANSACTION
        $db->beginTransaction();

        // 1. INSERT THE ANNOUNCEMENT AND GRAB ITS NEW ID
        $insertSql = "INSERT INTO announcements (title, content, target_audience, posted_by) 
                      OUTPUT INSERTED.announcement_id 
                      VALUES (:title, :content, :audience, :admin_id)";
        
        $stmt = $db->prepare($insertSql);

        // Sanitize and bind
        $title = htmlspecialchars(strip_tags($data->title));
        $content = htmlspecialchars(strip_tags($data->content));
        
        $stmt->bindParam(":title", $title);
        $stmt->bindParam(":content", $content);
        $stmt->bindParam(":audience", $data->target_audience);
        $stmt->bindParam(":admin_id", $data->admin_id);
        
        $stmt->execute();
        
        // Grab the brand new ID generated by SQL Server
        $row = $stmt->fetch(PDO::FETCH_ASSOC);
        $new_id = $row['announcement_id'];

        // 2. INSERT INTO AUDIT LOGS
        $auditSql = "INSERT INTO audit_logs (action_type, table_affected, performed_by, details) 
                     VALUES ('Announcement Posted', 'announcements', :admin_id, :details)";
        
        $auditStmt = $db->prepare($auditSql);
        
        $details = "Posted: " . $title;
        
        $auditStmt->bindParam(":admin_id", $data->admin_id);
        $auditStmt->bindParam(":details", $details);
        $auditStmt->execute();

        // ✅ COMMIT TRANSACTION
        $db->commit();

        http_response_code(200);
        echo json_encode(array(
            "message" => "Announcement posted successfully.",
            "announcement_id" => $new_id
        ));

    } catch (Exception $e) {
        // ❌ ROLLBACK TRANSACTION
        $db->rollBack();
        http_response_code(500);
        echo json_encode(array("message" => "Transaction failed: " . $e->getMessage()));
    }
} else {
    http_response_code(400);
    echo json_encode(array("message" => "Incomplete data. Cannot post announcement."));
}
?>